#!/usr/bin/env python3
"""Single-insight Immo-Eliza report → rental yield by municipality.

This is the 3rd insight from ``top10insights.py`` (gross rental yield ranked by
area, the diverging horizontal bar) on its own page. It reuses the cleaning,
styling and chart logic from that module — nothing is re-derived here — and
bundles just that one insight, plus the Plotly runtime, into a single offline
HTML file.

Usage
-----
    python src/yieldinsight.py
    # or override paths:
    IMMO_DATA=/path/to/raw IMMO_OUT=/path/to/out.html python src/yieldinsight.py

Defaults (resolved relative to this file):
    data in  : ../data/raw/forsale.csv , ../data/raw/torent.csv
    html out : ../data/yieldinsight.html

Dependencies: pandas, numpy, plotly  (no scikit-learn / no network needed).
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import plotly.io as pio
from plotly.offline import get_plotlyjs

# Make the sibling module importable however this script is launched
# (``python src/yieldinsight.py`` or ``python -m src.yieldinsight``).
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from top10insights import (  # noqa: E402  (import after sys.path tweak)
    CSS,
    PLOTLY_CFG,
    area_yield_table,
    insight_yield_bars,
    load_clean,
)

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
DATA_DIR = Path(os.environ.get("IMMO_DATA", str(HERE.parent / "data" / "raw")))
OUT_HTML = Path(os.environ.get("IMMO_OUT", str(HERE.parent / "data" / "yieldinsight.html")))
FORSALE = DATA_DIR / "forsale.csv"
TORENT = DATA_DIR / "torent.csv"


# --------------------------------------------------------------------------- #
# HTML assembly — one insight only
# --------------------------------------------------------------------------- #
def render(section, n_sale, n_rent, n_areas):
    plotly_js = get_plotlyjs()
    chart_html = pio.to_html(section["chart"], full_html=False, include_plotlyjs=False,
                             div_id=f"chart{section['n']}", config=PLOTLY_CFG)
    chips = "".join(f'<span class="chip"><b>{v}</b>{k}</span>' for k, v in section["chips"])
    extra = f'<p class="extra">{section["extra"]}</p>' if section.get("extra") else ""
    tag = {"buyer": "for buyers", "investor": "for investors",
           "both": "buyers &amp; investors"}[section["audience"]]

    return f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Immo Eliza · Rental Yield by Municipality</title>
<style>{CSS}</style>
<script>{plotly_js}</script></head><body>
<header class="hero">
  <div class="kicker">Immo Eliza · Belgian residential market</div>
  <h1>{section['title']}</h1>
  <p class="lede">Gross rental yield ranked across Belgian municipalities, recomputed from
     {n_sale:,} sale &amp; {n_rent:,} rental listings with the model’s market-bound cleaning
     rules — for investors hunting the strongest cash-on-cash return.</p>
  <div class="meta">
    <div class="pill"><b>{n_sale:,}</b><span>clean sale listings</span></div>
    <div class="pill"><b>{n_rent:,}</b><span>clean rental listings</span></div>
    <div class="pill"><b>{n_areas}</b><span>municipalities matched</span></div>
    <div class="pill"><b>3</b><span>regions · whole of Belgium</span></div>
  </div></header><div class="wrap">
  <section class="insight" id="i{section['n']}">
    <div class="ihead">
      <div class="badge">%</div>
      <div class="itext"><h2>{section['title']}<span class="tag">{tag}</span></h2>
        <p class="finding">{section['finding']}</p></div>
    </div>
    <div class="chips">{chips}</div>
    {extra}
    <div class="chart">{chart_html}</div>
    <p class="why">{section['why']}</p>
  </section>
</div><footer>
  <b>Method.</b> Sale and rent CSVs are cleaned with the production guard rails
  (sale price <code>€25k–€15M</code>, rent <code>€200–€25k</code>, living area <code>9–3000&nbsp;m²</code>,
  €/m² recomputed as price ÷ surface and bounded). Yields are gross
  (<code>median rent €/m² × 12 ÷ median sale €/m²</code>) over municipalities with ≥15 listings on each
  side. NaNs are dropped per metric. Chart is interactive — hover for the underlying values.
  Generated by <code>src/yieldinsight.py</code>.
</footer></body></html>"""


def main():
    print(f"reading  {FORSALE}")
    print(f"reading  {TORENT}")
    sale = load_clean(FORSALE, "sale")
    rent = load_clean(TORENT, "rent")
    print(f"clean sale={len(sale):,}  clean rent={len(rent):,}")

    area = area_yield_table(sale, rent)
    print(f"matched yield areas (n>=15 both sides): {len(area)}")

    section = insight_yield_bars(sale, rent, area)
    html = render(section, len(sale), len(rent), len(area))
    OUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUT_HTML.write_text(html, encoding="utf-8")
    kb = OUT_HTML.stat().st_size / 1024
    print(f"\nwrote {OUT_HTML}  ({kb:,.0f} KB, 1 insight)")


if __name__ == "__main__":
    main()
